### PR TITLE
GCC: upstream RTL warning patch

### PR DESCRIPTION
**Pull request by mistydemeo**
Upstream patch: https://gcc.gnu.org/pipermail/gcc-patches/2021-November/583031.html

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103026

### CODE REVIEW

**Comment by Bo98** [comment]
You'll probably actually want patch v2: https://gcc.gnu.org/pipermail/gcc-patches/2021-November/583134.html

**Comment by mistydemeo** [comment]
Good catch, I was going by the link on the issue rather than following up the discussion.

**Comment by fxcoudert** [comment]
Hi @mistydemeo, just saw this, can you give a bit more context? As as I read from bugzilla and the GCC mailing-list, the issue is not a bug in GCC, it's a limitation of the C preprocessor model. The patch introduces a new warning, which is nice, but it does not fix any critical issue, and the patch itself has not been accepted into GCC mainline (and it looks like even the option name itself is still being debated). And if it's accepted, it's not determined yet whether it will be considered for GCC 11 backport at this point.

I'm a bit worried that we jumped the gun here.

**Comment by carlocab** [comment]
Some context from Slack: https://www.lightbluetouchpaper.org/2021/11/01/trojan-source-invisible-vulnerabilities/ See also the #security channel.

That said this patch doesn't seem to produce warnings for at least some of the test cases from the disclosure, so I'm wondering if the patch is incomplete.

**Comment by mistydemeo** [comment]
It's entirely possible we jumped the gun. I'm happy to pull the patch back out if you want to wait and see what happens.

**Comment by fxcoudert** [comment]
The issue is serious, affects multiple languages, multiple compilers, because it is baked into the design of languages. (I'm pretty sure it's used in a couple of entries in the International Obfuscated C Code Contest https://www.ioccc.org, or this one: https://blog.soliditylang.org/2020/12/03/solidity-underhanded-contest-winners/)

Whatever we ship will only be a bandaid, not a fix, and it may even be a partial bandaid (not all cases may be detectable). It may also have false positives, due to lack of wide testing.

Clearly GCC developers don't consider it a GCC bug, even less a GCC security bug, but a diagnostic improvement. So I doubt anything "final" is decided fast (in the next couple of days).  So we have to make our own choice: now that we have added a preliminary version of the patch, what do we do?

1. If we keep it, we risk getting reports from confused users, or people start using it and discover later the option name or meaning has changed.
2. If we remove it and rev-bump, a lot of people who don't care get two downloads and installs of GCC, which is a huge package
3. If we remove it and don't rev-bump, well, many users will still have downloaded it in the meantime.

I don't think we want 1, but I have no idea whether 2 or 3 is better for users.

**Comment by SMillerDev** [comment]
I wouldn't revision bump for the removal. But we can let the bottles update so that anyone who installs it new gets the non-patched bottles.

**Comment by carlocab** [comment]
GCC is about to be rev bumped at https://github.com/Homebrew/homebrew-core/pull/89193.

I suggest we include the patch removal there so we don't have to worry about whether rev-bumping is the right thing to do or not.

**Comment by mistydemeo** [comment]
Good idea, let's remove it then.

**Pull request merged**
