### PR TITLE
add patches for shogun 6.1.3

### PR DESCRIPTION
**Pull request by vigsterkr**

### CODE REVIEW

**Comment by ilovezfs** [comment]
What upstream commits do these correspond to?

**Comment by vigsterkr** [comment]
https://github.com/shogun-toolbox/shogun/commit/6db834fb4ca9783b6e5adfde808d60ebfca0abc9
https://github.com/shogun-toolbox/shogun/commit/ff8840ce0e0091d7619dacdf84819ea19872baf4

but as you will see it cannot be directly applied

**Comment by vigsterkr** [comment]
one of them could be if it wouldn't touch other unrelated parts of the code...

**Comment by ilovezfs** [comment]
Thanks @vigsterkr!

**Pull request merged**
