### PR TITLE
license: tweaks

### PR DESCRIPTION
**Pull request by DomT4**
Open for discussion.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Makes sense to me, thanks @DomT4.

**Comment by MikeMcQuaid** [comment]
Although this just broke the detection of this license due to the additional text, I think. I wonder if it's worth changing the license text entirely?

**Comment by DomT4** [comment]
Apologies, the license info box doesn't seem to appear on forks so I wasn't able to check that.

I guess GitHub _(or rather the gem it uses IIRC)_ is correct to be wary; adding or removing phrasing from a license could theoretically legally make it a custom license, but I'll leave that discussion down to SFC if it proves necessary 😅.

It's difficult with patches because patches contributed by Homebrew contributors are presumably offered under the same BSD license Homebrew uses, but we hold plenty of patches that originated from MacPorts who use the slightly less friendly 3-clause BSD, and we hold patches from a variety of upstreams who use a variety of "free" licenses.

Maybe it's worth removing this text from the license & acknowledging the somewhat complicated situation in the `README` or such instead. Ideally we'd have done a better job acknowledging patch origins over time but I'm by no means blame-free on that one.

**Comment by MikeMcQuaid** [comment]
> Maybe it's worth removing this text from the license & acknowledging the somewhat complicated situation in the README or such instead. Ideally we'd have done a better job acknowledging patch origins over time but I'm by no means blame-free on that one.

Yeh, I agree. It may be worth removing the licenses entirely and replacing them with just the line you added.

**Pull request merged**
