### PR TITLE
tinyscheme: Amend makefile patch to include init.scm.

### PR DESCRIPTION
**Pull request by woodruffw**
Reference: https://github.com/Homebrew/formula-patches/pull/19#issuecomment-233226441

### CODE REVIEW

**Comment by ilovezfs** [comment]
@woodruffw not sure it will make any difference ultimately, but do you mean
```
 -DInitFile="\"$(INITDEST)/init.scm"\"
```
or
```
 -DInitFile="\"$(INITDEST)/init.scm\""
```

**Comment by woodruffw** [comment]
Looks like this mistake existed all the way back in the [original patch](https://github.com/Homebrew/homebrew-core/pull/999/files#diff-61bbd91cb4e8c2df65b671c3472f934bL51). We probably want the escapes on the inside, so I'll fix that.

**Comment by UniqMartin** [comment]
Both variants are correct. It's just that the escaped `"` outside of the string looks a bit more odd (and unbalanced) to the human eye. The shell doesn't care and sees the exact same string.

Am I missing something or are we about to start maintaining boneyarded formulae with this? 😀 I guess since it's fixing an omission that happened during the migration, it's a fair move.

**Comment by ilovezfs** [comment]
>Both variants are correct.

Yeah, I tested both, and it didn't seem to make any actual difference but still was hard to imagine the reversal had been intentional.

>Am I missing something or are we about to start maintaining boneyarded formulae with this? :grinning: 

Yes, this occurred to me, too. :see_no_evil: But again this is an example where having formula-patches be a separate repository creates confusion since there's no policy currently (at least not one I'm aware of) about whether patches in formula-patches for boneyarded formulae should or should not be removed. If we're not removing them, I suppose there's no harm in making them correct, though.

**Comment by woodruffw** [comment]
Yeah, I wasn't really sure how to proceed on this one...

Since it was my mistake originally during the transition to the boneyard, I figured it was best to correct a trivial breakage like this one.

**Comment by UniqMartin** [comment]
> But again this is an example where having formula-patches be a separate repository creates confusion since there's no policy currently (at least not one I'm aware of) about whether patches in formula-patches for boneyarded formulae should or should not be removed.

There isn't currently a policy, but I think it could make sense to remove patches that are no longer referenced by any formula in an up-to-date `master` of any of the `Homebrew/homebrew-*` tap repositories. All `patch do` blocks should be referencing a specific commit, so they will continue to work unless we completely remove this repository in its entirety. The only downside might be that historic and no longer needed patches are harder to discover.

And yes, it would be easier (also in the contribution process), if patches lived in the same repository like the corresponding formula and could be added, updated, removed in lockstep.

> If we're not removing them, I suppose there's no harm in making them correct, though.

Agreed. As usual, this will also require an update to the formula to adjust the patch URL and the corresponding `sha256` line.

**Comment by woodruffw** [comment]
> Agreed. As usual, this will also require an update to the formula to adjust the patch URL and the corresponding sha256 line.

Yep. I'll have this pushed when I get home.

**Comment by UniqMartin** [comment]
No rush, as long as it's not completely forgotten! 😸

**Comment by UniqMartin** [comment]
I wonder how many patches were added here but ultimately never referenced in a formula.

**Comment by woodruffw** [comment]
> I wonder how many patches were added here but ultimately never referenced in a formula.

We could probably find out with a script against formulae in core/the aux taps/boneyard. I bet quite a few formulae have dropped their patches (without deleting them here) due to upstream fixes.

**Comment by ilovezfs** [comment]
I'd prefer that we move the patches all to their respective taps and discard the ones that aren't referenced along the way.

**Pull request merged**
