### PR TITLE
freeimage: add linux patch

### PR DESCRIPTION
**Pull request by iMichka**
This is an equivalent to the mac patch,
taken from:
https://gist.githubusercontent.com/davydden/5a4f348108d3c9110299/raw/3396840ff71c639d848ce552de9124462777ab97/freeimage.patch

### CODE REVIEW

**Comment by SMillerDev** [comment]
Has it been upstreamed?

**Comment by iMichka** [comment]
The Mac patch was added here: https://github.com/Homebrew/formula-patches/commit/4dcf52867baa32f038fa2ab1285fd1364eb65846

Both patches do almost the same, but would need to be merged together and upstreamed.

Upstream's last change is from July 2020: https://sourceforge.net/p/freeimage/svn/HEAD/tree/, it looks like a smaller project, with not that much activity. I do not have much time to invest in this right now.

I definitively are in favour of reducing the number of patches and be more strict about them: I can start that project in 2022 when I'm done with the linuxbrew-core merge :D

**Comment by SMillerDev** [comment]
Can you at least make an issue upstream about it?

**Review by SMillerDev — APPROVED** [review]

**Comment by iMichka** [comment]
I notified upstream that we were using these patches: https://sourceforge.net/p/freeimage/patches/145/

**Pull request merged**
