### PR TITLE
qt5: Workaround for macdeployqt tool

### PR DESCRIPTION
**Pull request by cawka**
https://bugreports.qt.io/browse/QTBUG-56814

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
As mentioned in https://github.com/Homebrew/homebrew-core/pull/8007: @cawka This patch needs and merged on https://codereview.qt-project.org/ before we'll accept it, I'm afraid.

**Comment by lparsons** [comment]
Seems like the patch was merged upstream (at least in dev https://codereview.qt-project.org/#/c/180825/). Any chance we can get this workaround merged while we wait for a new QT release?

**Comment by MikeMcQuaid** [comment]
upstream commit (that should be linked in the relevant PR): https://github.com/qt/qttools/commit/8f9b747f030bb41556831a23ec2a8e7e76fb7dc0#diff-2b6e250f93810fd9bcf9bbecf5d2be88

**Comment by ilovezfs** [comment]
Added to the formula in https://github.com/Homebrew/homebrew-core/pull/14766.

**Pull request merged**
