### PR TITLE
Removed patch no longer needed since OpenCSG-1.4.1

### PR DESCRIPTION
**Pull request by kintel**
Depends on Homebrew/homebrew-core#5088

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Is this patch already used in an active formula or is this for a new one? Thanks!

**Comment by kintel** [comment]
The original patch is used in an existing formula.
The updated patch is needed by a pull request to update the formula to a new upstream version

**Comment by MikeMcQuaid** [comment]
In that case, mind using a new filename? Thanks!

**Comment by zmwangx** [comment]
Please rename and split into two commits. The two patches are completely unrelated.

**Comment by zmwangx** [comment]
(A more informative name would be nice.)

**Pull request merged**
