### PR TITLE
Revert "bash: add patch"

### PR DESCRIPTION
**Pull request by ilovezfs**
This reverts commit 8dc8edfc1e07f25111d1a93db09bd1ec2d4ea0ca.

We're using only upstream (+ mirrors) patch urls now.

### CODE REVIEW

**Comment by DomT4** [comment]
I'd be tempted to keep this one in case there are people still using laughably outdated Homebrew installations, but `¯\_(ツ)_/¯`

**Comment by ilovezfs** [comment]
I think we never actually committed it to master using the patch.

**Comment by DomT4** [comment]
Oh, didn't we? Feel free to set 🔥 to it then.

**Comment by ilovezfs** [comment]
Yeah, I feel like charging it rent for the months of squatting.

**Comment by DomT4** [comment]
It's stayed so long we're lucky Stallman hasn't petitioned us to rename this repo `GNU/patches`.

**Pull request closed without merging**
