### PR TITLE
libmcrypt: patch for 2.5.8

### PR DESCRIPTION
**Pull request by shivammathur**
This patches `config.sub` and `config.guess` files in `libmcrypt` from the new ones in `automake` `1.16.3`.

- https://git.savannah.gnu.org/cgit/automake.git/tree/lib/config.guess?h=v1.16.3
- https://git.savannah.gnu.org/cgit/automake.git/tree/lib/config.sub?h=v1.16.3

This will allow `libmcrypt` and `mcrypt` to build on Apple silicon.

### CODE REVIEW

**Comment by carlocab** [comment]
Are there no upstream commits we can use as patches?

**Comment by shivammathur** [comment]
@carlocab No, the last update to `libmcrypt` was in 2007
https://sourceforge.net/projects/mcrypt/files/

**Comment by carlocab** [comment]
>No, the last update to `libmcrypt` was in 2007

That doesn't bode well for the formula. Does it work if you replace `mcrypt`'s `config.guess` and `config.sub` with the ones from the automake repo?

**Comment by shivammathur** [comment]
@carlocab 
Yes, I was able to build it on apple silicon by applying this patch.

Added patch to `mcrypt.rb`

```
--- a/Formula/mcrypt.rb
+++ b/Formula/mcrypt.rb
@@ -24,6 +24,11 @@ class Mcrypt < Formula
   resource "libmcrypt" do
     url "https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz"
     sha256 "e4eb6c074bbab168ac47b947c195ff8cef9d51a211cdd18ca9c9ef34d27a373e"
+
+    patch do
+      url "https://raw.githubusercontent.com/Homebrew/formula-patches/0921ad7957226b22b1e9679d097016d53031f081/mcrypt/libmcrypt-2.5.8.patch"
+      sha256 "3e61535874c707610354d07ada5201992563e128c18aa2181d2b2e3cc46a0d42"
+    end
   end
```

`brew install -s mcrypt`

```
==> Downloading https://homebrew.bintray.com/bottles/mhash-0.9.9.9.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/ffe49c713858a544600ff3fa9e6e977f4aa76d17a4ddee9bcf9d126ee8eae984--mhash-0.9.9.9.arm64_big_sur.bottle.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/0921ad7957226b22b1e9679d097016d53031f081/mcrypt/libmcrypt-2.5.8.patch
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/46f956fabe3fc11dc9cabf3935cd7880d20e03ed9daef71d4a26e7bf055cdb96--libmcrypt-2.5.8.tar.gz
==> Downloading https://downloads.sourceforge.net/project/mcrypt/MCrypt/2.6.8/mcrypt-2.6.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/ab0438603e44b501e991c1e6e45e848e4bba78e9e463678f173296d72c9cfc0a--mcrypt-2.6.8.tar.gz
==> Installing dependencies for mcrypt: mhash
==> Installing mcrypt dependency: mhash
==> Pouring mhash-0.9.9.9.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mhash/0.9.9.9: 20 files, 516.2KB
==> Installing mcrypt
==> Patching
==> Patching libmcrypt
==> Applying libmcrypt-2.5.8.patch
patching file config.guess
patching file config.sub
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share/man
==> make install
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --with-libmcrypt-prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share
==> make install
🍺  /opt/homebrew/Cellar/mcrypt/2.6.8: 19 files, 471.8KB, built in 27 seconds
Removing: /Users/administrator/Library/Caches/Homebrew/mcrypt--patch--3e61535874c707610354d07ada5201992563e128c18aa2181d2b2e3cc46a0d42.patch... (128.8KB)
```

`brew test mcrypt`

```
brew test mcrypt
==> Testing mcrypt
==> /opt/homebrew/Cellar/mcrypt/2.6.8/bin/mcrypt --key TestPassword --force test.txt
==> /opt/homebrew/Cellar/mcrypt/2.6.8/bin/mcrypt --key TestPassword --decrypt test.txt.nc
```

`Macports` was also able to build `libmcrypt` using the same process.
https://github.com/macports/macports-ports/commit/25c865e2511982b427904b661f0f6302f3edf430
https://build.macports.org/builders/ports-11_arm64-builder/builds/9591

**Comment by carlocab** [comment]
I don't mean using a patch. Patches are a bit finicky. Can we just replace the existing `config.guess` and `config.sub` wholesale without patching?

**Comment by shivammathur** [comment]
Yes, that would also work, adding `automake` as a build dependency and copying the config files from `automake`.

```patch
diff --git a/Formula/mcrypt.rb b/Formula/mcrypt.rb
index bb1bd1a4fe..6c63cde33f 100644
--- a/Formula/mcrypt.rb
+++ b/Formula/mcrypt.rb
@@ -17,6 +17,7 @@ class Mcrypt < Formula
     sha256 "55b9b6cb471b312208afddc9bbc9caaf8be6043d2b1cc7e32161633f83e226e5" => :mojave
   end
 
+  depends_on "automake" => :build
   depends_on "mhash"
 
   uses_from_macos "zlib"
@@ -35,6 +36,9 @@ class Mcrypt < Formula
     ENV.append "CFLAGS", "-Wno-implicit-function-declaration"
 
     resource("libmcrypt").stage do
+      %w[config.guess config.sub].each do |fn|
+        cp "#{Formula["automake"].opt_prefix}/share/automake-#{Formula["automake"].version.major_minor}/#{fn}", fn
+      end
       system "./configure", "--prefix=#{prefix}",
                             "--mandir=#{man}"
       system "make", "install"
```

`brew install -s mcrypt`

```zsh
==> Downloading https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/46f956fabe3fc11dc9cabf3935cd7880d20e03ed9daef71d4a26e7bf055cdb96--libmcrypt-2.5.8.tar.gz
==> Downloading https://downloads.sourceforge.net/project/mcrypt/MCrypt/2.6.8/mcrypt-2.6.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/ab0438603e44b501e991c1e6e45e848e4bba78e9e463678f173296d72c9cfc0a--mcrypt-2.6.8.tar.gz
==> Patching
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share/man
==> make install
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --with-libmcrypt-prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share
==> make install
🍺  /opt/homebrew/Cellar/mcrypt/2.6.8: 24 files, 543.5KB, built in 25 seconds
```

**Comment by shivammathur** [comment]
@carlocab Let me know if you prefer this method.

**Comment by carlocab** [comment]
Yes, that's better, as it's a whole lot more transparent than the patch. Leave a comment before the `depends_on "automake"` line that it should be removed if/when `mcrypt` is updated (if it ever will be...).

**Comment by shivammathur** [comment]
@carlocab `autoreconf` is not required if we are copying the config files from automake.

On testing, `autoreconf` would also work. It would need adding `autconf` and `libtool` as build dependencies, but I would prefer to copy config files from automake.

```patch
diff --git a/Formula/mcrypt.rb b/Formula/mcrypt.rb
index bb1bd1a4fe..3b9ab26bc0 100644
--- a/Formula/mcrypt.rb
+++ b/Formula/mcrypt.rb
@@ -17,6 +17,9 @@ class Mcrypt < Formula
     sha256 "55b9b6cb471b312208afddc9bbc9caaf8be6043d2b1cc7e32161633f83e226e5" => :mojave
   end
 
+  depends_on "autoconf" => :build
+  depends_on "automake" => :build
+  depends_on "libtool" => :build
   depends_on "mhash"
 
   uses_from_macos "zlib"
@@ -35,6 +38,7 @@ class Mcrypt < Formula
     ENV.append "CFLAGS", "-Wno-implicit-function-declaration"
 
     resource("libmcrypt").stage do
+      system "autoreconf", "--verbose", "--install", "--force"
       system "./configure", "--prefix=#{prefix}",
                             "--mandir=#{man}"
       system "make", "install"
```

`brew install -s mcrypt`

```zsh
==> Downloading https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/46f956fabe3fc11dc9cabf3935cd7880d20e03ed9daef71d4a26e7bf055cdb96--libmcrypt-2.5.8.tar.gz
==> Downloading https://downloads.sourceforge.net/project/mcrypt/MCrypt/2.6.8/mcrypt-2.6.8.tar.gz
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/ab0438603e44b501e991c1e6e45e848e4bba78e9e463678f173296d72c9cfc0a--mcrypt-2.6.8.tar.gz
==> Patching
==> autoreconf --verbose --install --force
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share/man
==> make install
==> ./configure --prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --with-libmcrypt-prefix=/opt/homebrew/Cellar/mcrypt/2.6.8 --mandir=/opt/homebrew/Cellar/mcrypt/2.6.8/share
==> make install
🍺  /opt/homebrew/Cellar/mcrypt/2.6.8: 23 files, 519.4KB, built in 31 seconds
```

**Comment by carlocab** [comment]
That's fine; we can just copy the needed config files then. Thanks for looking into this!

**Pull request closed without merging**
