### PR TITLE
opencv: patch for DNN module using openvino 2024.0.0

### PR DESCRIPTION
**Pull request by artanokhov**
This patch for OpenCV DNN module to work with OpenVINO 2024.0.0

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Thanks @artanokhov, can you please sign your commit as required?

> Merging is blocked
> The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

---

Difference between this patch and https://github.com/opencv/opencv/commit/6da2ddcf0e614ecace25c1ad07c8a51054a7e9a2, for reference:

```shell
diff \
  <(curl https://raw.githubusercontent.com/Homebrew/formula-patches/da53088f381399813eb9c7e2c256e8b1af5fa220/opencv/openvino2024.patch) \
  <(curl https://github.com/opencv/opencv/commit/6da2ddcf0e614ecace25c1ad07c8a51054a7e9a2.diff)
```

<details>

```diff
2c2
< index 319fd5bf0a..9a2eb38b03 100644
---
> index 319fd5bf0ad2..9a2eb38b0394 100644
74c74
< index 7eeb62bcf6..6e7b9f9be5 100644
---
> index 18aa8cc3b649..6e7b9f9be5aa 100644
138c138
< @@ -103,7 +71,7 @@ public:
---
> @@ -103,7 +71,7 @@ class NgraphCustomOp: public ov::op::Op {
147c147
< @@ -131,265 +99,13 @@ public:
---
> @@ -131,265 +99,13 @@ class NgraphCustomOp: public ov::op::Op {
507c507
< -                    cv::convertFp16(floats, halfs);
---
> -                    floats.convertTo(halfs, CV_16F);
1069c1069
< index 8672f1a3c2..19e07d62ac 100644
---
> index 8672f1a3c2ea..19e07d62ac32 100644
1096c1096
< @@ -44,8 +44,8 @@ public:
---
> @@ -44,8 +44,8 @@ class InfEngineNgraphNet
1107c1107
< @@ -56,15 +56,11 @@ public:
---
> @@ -56,15 +56,11 @@ class InfEngineNgraphNet
1126c1126
< @@ -74,14 +70,14 @@ public:
---
> @@ -74,14 +70,14 @@ class InfEngineNgraphNet
1143c1143
< @@ -93,13 +89,13 @@ public:
---
> @@ -93,13 +89,13 @@ class InfEngineNgraphNode : public BackendNode
1160c1160
< @@ -118,11 +114,7 @@ public:
---
> @@ -118,11 +114,7 @@ class NgraphBackendWrapper : public BackendWrapper
1172c1172
< @@ -132,7 +124,7 @@ public:
---
> @@ -132,7 +124,7 @@ class NgraphBackendWrapper : public BackendWrapper
1181c1181
< @@ -145,11 +137,11 @@ public:
---
> @@ -145,11 +137,11 @@ class NgraphBackendLayer : public Layer
1197c1197
< index 7ef169deea..3fbf8cd191 100644
---
> index 7ef169deea04..3fbf8cd19177 100644
1209c1209
< @@ -250,11 +248,11 @@ public:
---
> @@ -250,11 +248,11 @@ class BatchNormLayerInt8Impl CV_FINAL : public BatchNormLayerInt8
1227c1227
< index ba9b31fe35..2695cb6d56 100644
---
> index a5a98c976422..603100ae117e 100644
1230c1230
< @@ -573,8 +573,8 @@ public:
---
> @@ -573,8 +573,8 @@ class ConvolutionLayerInt8Impl CV_FINAL : public BaseConvolutionLayerInt8Impl
1241c1241
< @@ -592,18 +592,18 @@ public:
---
> @@ -592,18 +592,18 @@ class ConvolutionLayerInt8Impl CV_FINAL : public BaseConvolutionLayerInt8Impl
1266c1266
< @@ -627,31 +627,31 @@ public:
---
> @@ -627,31 +627,31 @@ class ConvolutionLayerInt8Impl CV_FINAL : public BaseConvolutionLayerInt8Impl
1315c1315
< @@ -659,12 +659,12 @@ public:
---
> @@ -659,12 +659,12 @@ class ConvolutionLayerInt8Impl CV_FINAL : public BaseConvolutionLayerInt8Impl
1332c1332
< @@ -672,9 +672,9 @@ public:
---
> @@ -672,9 +672,9 @@ class ConvolutionLayerInt8Impl CV_FINAL : public BaseConvolutionLayerInt8Impl
1345c1345
< index 2f40a4039f..f522efa0c1 100644
---
> index 5c533840f393..f522efa0c1e4 100644
1348c1348
< @@ -253,24 +253,26 @@ public:
---
> @@ -253,26 +253,26 @@ class ActivationLayerInt8Impl CV_FINAL : public ActivationLayerInt8
1373c1373,1374
< +        } else if (type == "HardSwishInt8") {
---
>          } else if (type == "HardSwishInt8") {
> -            res = std::make_shared<ngraph::op::v4::HSwish>(input);
1385c1386
< index a3bb6ec2d6..214d11525a 100644
---
> index a3bb6ec2d6c7..214d11525a38 100644
1388c1389
< @@ -375,7 +375,7 @@ public:
---
> @@ -375,7 +375,7 @@ class EltwiseLayerInt8Impl CV_FINAL : public EltwiseLayerInt8
1397c1398
< @@ -389,9 +389,9 @@ public:
---
> @@ -389,9 +389,9 @@ class EltwiseLayerInt8Impl CV_FINAL : public EltwiseLayerInt8
1411c1412
< index ba5b0d79c1..5d13ba8f29 100644
---
> index 3a560ddda636..66911289908d 100644
1414c1415
< @@ -405,8 +405,8 @@ public:
---
> @@ -410,8 +410,8 @@ class FullyConnectedLayerInt8Impl CV_FINAL : public InnerProductLayerInt8
1425c1426
< @@ -414,15 +414,15 @@ public:
---
> @@ -419,15 +419,15 @@ class FullyConnectedLayerInt8Impl CV_FINAL : public InnerProductLayerInt8
1444c1445
< @@ -439,16 +439,16 @@ public:
---
> @@ -444,16 +444,16 @@ class FullyConnectedLayerInt8Impl CV_FINAL : public InnerProductLayerInt8
1469c1470
< @@ -457,9 +457,9 @@ public:
---
> @@ -462,9 +462,9 @@ class FullyConnectedLayerInt8Impl CV_FINAL : public InnerProductLayerInt8
1483c1484
< index b321d730f7..cfd04bd2f4 100644
---
> index b321d730f7f0..cfd04bd2f46e 100644
1494c1495
< @@ -284,22 +285,22 @@ public:
---
> @@ -284,22 +285,22 @@ class PoolingLayerInt8Impl CV_FINAL : public PoolingLayerInt8
1526c1527
< @@ -307,8 +308,8 @@ public:
---
> @@ -307,8 +308,8 @@ class PoolingLayerInt8Impl CV_FINAL : public PoolingLayerInt8
1538c1539
< index e50c4cea0e..25d48e3d17 100644
---
> index e50c4cea0e97..25d48e3d1794 100644
1541c1542
< @@ -191,7 +191,7 @@ public:
---
> @@ -191,7 +191,7 @@ class ScaleLayerInt8Impl CV_FINAL : public ScaleLayerInt8
1550c1551
< @@ -200,7 +200,7 @@ public:
---
> @@ -200,7 +200,7 @@ class ScaleLayerInt8Impl CV_FINAL : public ScaleLayerInt8
1559c1560
< @@ -222,17 +222,17 @@ public:
---
> @@ -222,17 +222,17 @@ class ScaleLayerInt8Impl CV_FINAL : public ScaleLayerInt8
1583c1584
< index 28c6837cca..e81b82b99f 100644
---
> index 28c6837cca09..e81b82b99fea 100644
1586c1587
< @@ -204,11 +204,11 @@ public:
---
> @@ -204,11 +204,11 @@ class SoftMaxLayerInt8Impl CV_FINAL : public SoftmaxLayerInt8
1602c1603
< index 1d95096e60..ccf5608317 100644
---
> index ccc8354b424f..3cdbdc222b9c 100644
1614c1615
< @@ -459,14 +457,10 @@ public:
---
> @@ -459,14 +457,10 @@ class BatchNormLayerImpl CV_FINAL : public BatchNormLayer
1634c1635
< index 16de23b15e..9723975723 100644
---
> index 16de23b15e19..9723975723c3 100644
1637c1638
< @@ -149,8 +149,8 @@ public:
---
> @@ -149,8 +149,8 @@ class BlankLayerImpl CV_FINAL : public BlankLayer
1649c1650
< index a5af16f32e..14834d2cd3 100644
---
> index 3b4b622b2ada..3a6466bd804d 100644
1660c1661
< @@ -397,7 +396,7 @@ public:
---
> @@ -397,7 +396,7 @@ class ConcatLayerImpl CV_FINAL : public ConcatLayer
1669c1670
< @@ -423,14 +422,14 @@ public:
---
> @@ -423,14 +422,14 @@ class ConcatLayerImpl CV_FINAL : public ConcatLayer
1690c1691
< index 2a1e27db56..0fe7c22782 100644
---
> index a3f510c496ac..2246c1632071 100644
1693c1694
< @@ -128,22 +128,22 @@ public:
---
> @@ -128,22 +128,22 @@ class ConstLayerImpl CV_FINAL : public ConstLayer
1725c1726
< index dd6fa7bc1d..85c9f1d8d6 100644
---
> index 3f4c5e40695b..a950ea18c26a 100644
1728c1729
< @@ -822,7 +822,7 @@ public:
---
> @@ -822,7 +822,7 @@ class ConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
1737c1738
< @@ -840,49 +840,49 @@ public:
---
> @@ -840,49 +840,49 @@ class ConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
1806c1807
< @@ -890,18 +890,18 @@ public:
---
> @@ -890,18 +890,18 @@ class ConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
1831c1832
< @@ -2251,13 +2251,13 @@ public:
---
> @@ -2252,13 +2252,13 @@ class DeConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
1847c1848
< @@ -2269,24 +2269,24 @@ public:
---
> @@ -2270,24 +2270,24 @@ class DeConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
1882c1883
< index a6f58f8983..e735242929 100644
---
> index 43373ca4dedf..6c29d6b8f493 100644
1885c1886
< @@ -138,23 +138,23 @@ public:
---
> @@ -138,23 +138,23 @@ class CropAndResizeLayerImpl CV_FINAL : public CropAndResizeLayer
1921c1922
< index 26f483a770..07f96e2a08 100644
---
> index 9a7a56fe7a85..c7b2272550d1 100644
1937c1938
< @@ -1012,26 +1008,26 @@ public:
---
> @@ -1012,26 +1008,26 @@ class DetectionOutputLayerImpl CV_FINAL : public DetectionOutputLayer
1975c1976
< @@ -1044,7 +1040,7 @@ public:
---
> @@ -1044,7 +1040,7 @@ class DetectionOutputLayerImpl CV_FINAL : public DetectionOutputLayer
1985c1986
< index 746db69603..f96a7f2f08 100644
---
> index 7de854c1797e..6b7909b1b7bb 100644
2201c2202
< index 49b3c02de3..37b8b1ba66 100644
---
> index 32caf29530df..e9363bcbea8d 100644
2204c2205
< @@ -899,24 +899,24 @@ public:
---
> @@ -899,24 +899,24 @@ class EltwiseLayerImpl CV_FINAL : public EltwiseLayer
2240c2241
< index 9ff3bec38b..48950601f2 100644
---
> index 9ff3bec38b6b..48950601f2fd 100644
2251c2252
< @@ -224,9 +225,9 @@ public:
---
> @@ -224,9 +225,9 @@ class FlattenLayerImpl CV_FINAL : public FlattenLayer
2265c2266
< index 1c27043f1a..0694c4bc69 100644
---
> index 29090652e139..4ff6fc74a420 100644
2268c2269
< @@ -794,20 +794,20 @@ public:
---
> @@ -787,20 +787,20 @@ class FullyConnectedLayerImpl CV_FINAL : public InnerProductLayer
2293c2294
< @@ -817,14 +817,14 @@ public:
---
> @@ -810,14 +810,14 @@ class FullyConnectedLayerImpl CV_FINAL : public InnerProductLayer
2314c2315
< index 821700c83e..8c7000a8e6 100644
---
> index 496d3871a236..fd10e9acdf78 100644
2317c2318
< @@ -285,45 +285,45 @@ public:
---
> @@ -285,45 +285,45 @@ class GemmLayerImpl CV_FINAL : public GemmLayer {
2377c2378
< index b43e9bbb7a..29f3732dc2 100644
---
> index b6427238f258..ae61f15656c9 100644
2380c2381
< @@ -225,33 +225,26 @@ public:
---
> @@ -225,33 +225,26 @@ class InstanceNormLayerImpl CV_FINAL : public InstanceNormLayer {
2423c2424
< index f3d2667a0a..aae5ff9f41 100644
---
> index 6ea1bee42a0d..5ebebbd32dcf 100644
2426c2427
< @@ -263,42 +263,35 @@ public:
---
> @@ -263,42 +263,35 @@ class LayerNormLayerImpl CV_FINAL : public LayerNormLayer
2479c2480
< index f8de64cb32..a86004ac18 100644
---
> index 7d212dc8889e..4863be2e3df2 100644
2482c2483
< @@ -483,8 +483,8 @@ public:
---
> @@ -483,8 +483,8 @@ class LRNLayerImpl CV_FINAL : public LRNLayer
2494c2495
< index c6cea65d87..2fccbde4ac 100644
---
> index 1e9a8dfebe1e..a571592dfb34 100644
2518c2519
< index 7ed6c64ae8..d81d585d4e 100644
---
> index d00887db3cab..aa645c17aee5 100644
2521c2522
< @@ -200,29 +200,29 @@ public:
---
> @@ -200,29 +200,29 @@ class MaxUnpoolLayerImpl CV_FINAL : public MaxUnpoolLayer
2563c2564
< index 43c33d82af..69a5bc8b1a 100644
---
> index 10ef1cfb34b2..d59e339ac45e 100644
2566c2567
< @@ -336,15 +336,11 @@ public:
---
> @@ -336,15 +336,11 @@ class MVNLayerImpl CV_FINAL : public MVNLayer
2585c2586
< index c988ec69f2..2b7b73c172 100644
---
> index c369a710a61d..e3a8b2a583d2 100644
2588c2589
< @@ -907,22 +907,32 @@ public:
---
> @@ -887,32 +887,32 @@ class NaryEltwiseLayerImpl CV_FINAL : public NaryEltwiseLayer
2616,2618c2617,2623
< +        // Ideally we should do this but int32 internal blobs are converted to float32 data type in inference.
< +        // TODO: Remove data type convertion when we have type inference.
< +        else if (op == OPERATION::MOD) {
---
>          // Ideally we should do this but int32 internal blobs are converted to float32 data type in inference.
>          // TODO: Remove data type convertion when we have type inference.
>          else if (op == OPERATION::MOD) {
> -            auto inp0_i64 = std::make_shared<ngraph::op::Convert>(inp0, ngraph::element::i64);
> -            auto inp1_i64 = std::make_shared<ngraph::op::Convert>(inp1, ngraph::element::i64);
> -            auto mod = std::make_shared<ngraph::op::v1::FloorMod>(inp0_i64, inp1_i64);
> -            node = std::make_shared<ngraph::op::Convert>(mod, ngraph::element::f32);
2623,2624c2628,2630
< +        }
< +        else if (op == OPERATION::FMOD)
---
>          }
>          else if (op == OPERATION::FMOD)
> -            node = std::make_shared<ngraph::op::v1::Mod>(inp0, inp1);
2630c2636
< index 431eeab82d..5dfb5d128b 100644
---
> index 723d3c7f7f28..d2324b2a9404 100644
2633c2639
< @@ -283,8 +283,8 @@ public:
---
> @@ -283,8 +283,8 @@ class NormalizeBBoxLayerImpl CV_FINAL : public NormalizeBBoxLayer
2644c2650
< @@ -292,13 +292,9 @@ public:
---
> @@ -292,13 +292,9 @@ class NormalizeBBoxLayerImpl CV_FINAL : public NormalizeBBoxLayer
2662c2668
< index f66d44b222..8bb8ab663d 100644
---
> index edb7f92413be..947bca86181e 100644
2665c2671
< @@ -278,14 +278,14 @@ public:
---
> @@ -268,14 +268,14 @@ class PaddingLayerImpl CV_FINAL : public PaddingLayer
2687c2693
< index 4e6ca2543d..a4f9181d45 100644
---
> index b7c8bcfdafa0..7304302314a0 100644
2690c2696
< @@ -475,9 +475,9 @@ public:
---
> @@ -475,9 +475,9 @@ class PermuteLayerImpl CV_FINAL : public PermuteLayer
2704c2710
< index fb980c4152..92c7a7f72c 100644
---
> index ba077bdcc44b..fbf075f7d3f3 100644
2723c2729
< @@ -588,20 +583,20 @@ public:
---
> @@ -588,20 +583,20 @@ class PoolingLayerImpl CV_FINAL : public PoolingLayer
2750c2756
< @@ -609,37 +604,33 @@ public:
---
> @@ -609,37 +604,33 @@ class PoolingLayerImpl CV_FINAL : public PoolingLayer
2799c2805
< index bf25927480..4cfffb6095 100644
---
> index 1dc40b48ce15..bb3aa99cd31f 100644
2818c2824
< @@ -513,23 +508,23 @@ public:
---
> @@ -513,23 +508,23 @@ class PriorBoxLayerImpl CV_FINAL : public PriorBoxLayer
2850c2856
< @@ -539,14 +534,14 @@ public:
---
> @@ -539,14 +534,14 @@ class PriorBoxLayerImpl CV_FINAL : public PriorBoxLayer
2869c2875
< @@ -560,9 +555,9 @@ public:
---
> @@ -560,9 +555,9 @@ class PriorBoxLayerImpl CV_FINAL : public PriorBoxLayer
2883c2889
< index 2f2a33cc6f..c7baf7870c 100644
---
> index d9df09c64214..66559ab9ffc7 100644
2899c2905
< @@ -344,7 +340,7 @@ public:
---
> @@ -344,7 +340,7 @@ class ProposalLayerImpl CV_FINAL : public ProposalLayer
2908c2914
< @@ -367,12 +363,12 @@ public:
---
> @@ -367,12 +363,12 @@ class ProposalLayerImpl CV_FINAL : public ProposalLayer
2926c2932
< index 38b809e0f9..5eecc9139d 100644
---
> index 159fd5f7e13a..409cdfa38b4e 100644
2937c2943
< @@ -122,7 +121,7 @@ public:
---
> @@ -122,7 +121,7 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
2946c2952
< @@ -473,55 +472,55 @@ public:
---
> @@ -473,55 +472,55 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
3032c3038
< @@ -534,20 +533,20 @@ public:
---
> @@ -534,20 +533,20 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
3063c3069
< @@ -555,13 +554,13 @@ public:
---
> @@ -555,13 +554,13 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
3082c3088
< @@ -596,53 +595,53 @@ public:
---
> @@ -596,53 +595,53 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
3168c3174
< index ac7d1abfb1..4a8686bae1 100644
---
> index 7281190cdd7e..986bb64c829b 100644
3184c3190
< @@ -205,7 +201,7 @@ public:
---
> @@ -205,7 +201,7 @@ class ReorgLayerImpl CV_FINAL : public ReorgLayer
3194c3200
< index a72236c472..f259629e96 100644
---
> index a72236c47268..f259629e9625 100644
3197c3203
< @@ -369,9 +369,9 @@ public:
---
> @@ -369,9 +369,9 @@ class ReshapeLayerImpl CV_FINAL : public ReshapeLayer
3211c3217
< index fe27748319..12a3b613e1 100644
---
> index 5b8b9f812ff7..bf8f1b674c4d 100644
3227c3233
< @@ -376,81 +372,39 @@ public:
---
> @@ -376,81 +372,39 @@ class ResizeLayerImpl : public ResizeLayer
3323c3329
< index 2a4e1a05d5..00ca4322f8 100644
---
> index 00b12813995c..4c2d585ce019 100644
3326c3332
< @@ -331,7 +331,7 @@ public:
---
> @@ -331,7 +331,7 @@ class ScaleLayerImpl CV_FINAL : public ScaleLayer
3335c3341
< @@ -346,31 +346,26 @@ public:
---
> @@ -346,31 +346,26 @@ class ScaleLayerImpl CV_FINAL : public ScaleLayer
3378c3384
< index c44d18182e..1947635214 100644
---
> index 08172f3cdb24..de302ec29194 100644
3381c3387
< @@ -768,14 +768,14 @@ public:
---
> @@ -768,14 +768,14 @@ class SliceLayerImpl : public SliceLayer
3405c3411
< index ff559e980a..56abc888e3 100644
---
> index 18f4d6b61ec0..239ad1574bb1 100644
3408c3414
< @@ -314,9 +314,9 @@ public:
---
> @@ -314,9 +314,9 @@ class SoftMaxLayerImpl CV_FINAL : public SoftmaxLayer
3421c3427
< index adcfea60f0..501a596e5d 100644
---
> index adcfea60f040..501a596e5d0a 100644
3437c3443
< @@ -146,7 +152,7 @@ public:
---
> @@ -146,7 +152,7 @@ class NetImplOpenVINO CV_FINAL : public Net::Impl
3648c3654
< index f9e3993d20..04f1da7c71 100644
---
> index f9e3993d206b..04f1da7c7150 100644
3890c3896
< index c5a2e58683..236b21b1a3 100644
---
> index c5a2e58683fb..236b21b1a3a6 100644
4006c4012
< index 5b77b10827..6f96289b80 100644
---
> index 5b77b1082766..6f96289b8052 100644
4009c4015
< @@ -111,7 +111,7 @@ public:
---
> @@ -111,7 +111,7 @@ class WebnnNet
4019c4025
< index c6667c7ad2..eff389035d 100644
---
> index c6667c7ad22d..eff389035d10 100644
4248c4254
<  void runCV(Backend backendId, Target targetId, const std::string& xmlPath, const std::string& binPath,
\ No newline at end of file
---
>  void runCV(Backend backendId, Target targetId, const std::string& xmlPath, const std::string& binPath,
```
</details>

**Comment by artanokhov** [comment]
> Thanks @artanokhov, can you please sign your commit as required?
> 
> > Merging is blocked
> > The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)
> 
> Also, can you confirm if OpenCV 4.9.0 builds with this patch?
> 
> Difference between this patch and [opencv/opencv@6da2ddc](https://github.com/opencv/opencv/commit/6da2ddcf0e614ecace25c1ad07c8a51054a7e9a2), for reference:
> 
> ```shell
> diff \
>   <(curl https://raw.githubusercontent.com/Homebrew/formula-patches/da53088f381399813eb9c7e2c256e8b1af5fa220/opencv/openvino2024.patch) \
>   <(curl https://github.com/opencv/opencv/commit/6da2ddcf0e614ecace25c1ad07c8a51054a7e9a2.diff)
> ```

Yeah, that's right it is backported patch prepared by @ilya-lavrenov; as for example this patch already submitted to conda-forge https://github.com/conda-forge/opencv-feedstock/pull/399

**Comment by artanokhov** [comment]
@ZhongRuoyu can we merge it?

**Comment by ZhongRuoyu** [comment]
@artanokhov Can you please sign the commit? As you can see merging is blocked if commits are not signed.

If you haven't set up your GPG key, I think the easiest way to get a signed commit is to first remove your commit from this branch, and then make your commit through GitHub UI (click "Add file" > "Upload files" on https://github.com/artanokhov/formula-patches/tree/opencv-dnn-ov2.0-patch).

**Comment by artanokhov** [comment]
@ZhongRuoyu now it have verified status.
I've also added patch for opencv G-API in addition to previous one

**Review by ZhongRuoyu — APPROVED** [review]
Thanks!

**Pull request merged**
