### PR TITLE
rm qt5/restore-pc-files-5.12.patch, becuase it's not needed since beta2

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by yurikoles** [comment]
@fxcoudert could you approve this?

**Comment by fxcoudert** [comment]
We typically don't remove patches here, keeping them for historical purposes.

**Comment by yurikoles** [comment]
We never shipped version with this patch, so I think It can be safely removed.

**Comment by fxcoudert** [comment]
Missed that, sorry.

**Pull request merged**
