### PR TITLE
Add a patch to improve libffi support for Apple Silicon

### PR DESCRIPTION
**Pull request by hjelmn**
The PR adds a patch that brings in improvements from Apple's libffi
(specifically libffi-26). These improvements are needed to use libffi
with ghc.

Commits:
https://github.com/libffi/libffi/commit/4c7bde32ea3af479babdf527d94f241282951cb9
https://github.com/libffi/libffi/pull/565

I added additional configure logic to ensure that FFI_TRAMPOLINE_WHOLE_DYLIB
is set on Apple Silicon (it is hard-coded to 1 in libffi-26 for aarch64).

Signed-off-by: Nathan Hjelm <hjelmn@cs.unm.edu>

### CODE REVIEW

**Comment by hjelmn** [comment]
Patch looks big because it includes generated files (configure, Makefile.in, etc).

**Comment by SMillerDev** [comment]
Van weer not use the upstream patches?

**Comment by hjelmn** [comment]
Sure. I will have to create one myself for the configury changes. If that is the preferred way the formula will have to depend on autoconf for build and call autoreconf.

**Comment by carlocab** [comment]
If you need autoreconf to use the upstream patches then it may be cleaner to just use this one. That way when the patch is outdated it's more easily noticed that it's no longer needed. The autoconf dependency, on the other hand, could stick for a while.

**Comment by hjelmn** [comment]
What is the status on this? I want to update the formula but I am waiting on this to go in first.

**Comment by carlocab** [comment]
Thanks, @hjelmn!

**Pull request merged**
