### PR TITLE
mysql: update `boost-check.patch`

### PR DESCRIPTION
**Pull request by bevanjkay**
Updates the patch to work with mysql `8.2.0` CMakeList.txt

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is this submitted upstream again?

**Comment by bevanjkay** [comment]
No it isn't. I think per last iteration of this patch it's homebrew specific.

**Comment by SMillerDev** [comment]
We should really still try to submit it, even if it's just for upstream to review

**Comment by Bo98** [comment]
We can probably ask for them to add an option.

The code we're patching out here is code that's unfortunately specific to their build environment and causes issues for us shipping it as it prevents having boost installed at the same time as MySQL, which is why we're forced to remove it. The reasons for upstream having the code do not apply to our superenv - we've never had an issue of Boost conflicting with MySQL.

**Review by Bo98 — APPROVED** [review]

**Comment by bevanjkay** [comment]
I don't have permission to merge this here, but it's approved. Since it is merged into `mysql` via the commit hash already, is it ok for someone with write permission to merge?

**Pull request merged**
